### ISSUE TITLE
Could gomodguard also be made to block 'replace' directives?

### ISSUE THREAD

**Issue by edwarnicke** [ryancurrah/gomodguard#2]
Thank you for gomodguard... it solves a very real problem.

Is it possible to have gomodguard also have an option to block 'replace' directives?

Generally, you want to exclude all 'local' replace directives from your upstream repo, and you often only want to *very* selectively allow any replace directives at all... it would be very helpful to be able to do that with gomodguard :)

**Comment by ryancurrah** [comment]
I do not think this would be to difficult thanks to golang.org/x/mod/modfile module. I can take a look at this in a week or so or feel free to submit a PR.
