### ISSUE TITLE
Tools import appears to be invalid

### ISSUE THREAD

**Issue by Skarlso** [ryancurrah/gomodguard#33]
When trying to build or compile this library included in another project that happens to use the build tag `tools` this library fails with:

```
tools.go:5:8: import "github.com/t-yuki/gocover-cobertura" is a program, not an importable package
```

Because that import statement appears to be incorrect. :)

**Comment by ryancurrah** [comment]
Note installing `golangci-lint` from source is not recommended. You should use a binary installation.

> Note: such go install/go get installation aren't guaranteed to work. We recommend using binary installation.

https://golangci-lint.run/usage/install/

**Comment by Skarlso** [comment]
Well I mean. Even if we don't install but I'm just a contributor who happens to have tools exported as a build tag I won't be able to build this project now, yes?
