### ISSUE TITLE
Blocked modules appears to be ignored in some cases

### ISSUE THREAD

**Issue by oschwald** [ryancurrah/gomodguard#39]
I haven't figured out an exact pattern, but it appears that blocked modules are not flagged in some instances:

```sh
$ cat .gomodguard.yaml
blocked:
  modules:
    - gotest.tools/v3/assert:
        recommendations:
          - github.com/stretchr/testify/assert
        reason: "We have standardized on `github.com/stretchr/testify/assert`."

$ git grep gotest.tools/v3/assert
build_test.go:  "gotest.tools/v3/assert"

$ gomodguard build_test.go
info: allowed modules, []
info: allowed module domains, []
info: blocked modules, [gotest.tools/v3/assert]
info: blocked modules with version constraints, []
```

If I change `gotest.tools/v3/assert` to another module used in the same file, it seems to work.

**Comment by Jeeyuen-Rick** [comment]
Hi, I tried to block github.com/gin-gonic/gin version 1.9.16 (last 2 lines) and seems to be ignored as well. Below is my config file. May you take a look. Thanks.

linters-settings:
  gomodguard:
    allowed:
      # List of allowed modules.
      # Default: []
      modules:
        - github.com/pborman/uuid
      # List of allowed module domains.
      # Default: []
      domains:
        - golang.org
    blocked:
      # List of blocked modules.
      # Default: []
      modules:
        # Blocked module.
        - github.com/uudashr/go-module:
      # List of blocked module version constraints.
      # Default: []
      versions:
        - github.com/mitchellh/go-homedir:
            version: "<= 1.1.0"                                    # Version constraint.
            reason: "testing if blocked version constraint works." # Reason why the version constraint exists.
        - cloud.google.com/go/compute:
            version: "!= 1.7.0"
        - sigs.k8s.io/kustomize/kyaml:                             # kustomize/kyaml
            version: "< 0.13.6"
        - sigs.k8s.io/kustomize/kyaml:                             # kustomize/kyaml
            version: "> 0.13.9"
        - sigs.k8s.io/structured-merge-diff/v4:
            version: "!= 4.2.1"
        - sigs.k8s.io/structured-merge-diff/v4:
            version: "!= 4.2.3"
        - sigs.k8s.io/yaml:
            version: "!= 1.3.0"
        - github.com/gin-gonic/gin:
            version: "== 1.9.16"
      domains:

**Comment by ryancurrah** [comment]
Thanks for the report and example config. I will look at this soon

**Comment by ryancurrah** [comment]
Ok so for @oschwald issue, they put the package name `gotest.tools/v3/assert` when they should be using the module name `gotest.tools/v3`. When I use that it works. @Jeeyuen-Rick I'll look at your use issue next.

**Comment by Jeeyuen-Rick** [comment]
I believe this is reasonable. Since I didn’t read the document carefully and assumed ‘==’ instead of ‘=’. Thank you again for catching my mistake.
